#!/usr/bin/env bash
set -euo pipefail

#############################################
# SPK Builder for PHP 8.3 - Synology Package
# Standalone builder without spksrc dependency
#############################################

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SPK_DIR="$PROJECT_ROOT/spk/php83"
BUILD_DIR="$PROJECT_ROOT/dist/build"
OUTPUT_DIR="$PROJECT_ROOT/dist"

# Package metadata
PKG_NAME="php83"
PKG_VERSION="8.3.8"
PKG_BUILD="0001"
PKG_ARCH="geminilake"
PKG_FULL_VERSION="${PKG_VERSION}-${PKG_BUILD}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Clean previous build
clean_build() {
    log_info "Cleaning previous build..."
    rm -rf "$BUILD_DIR"
    mkdir -p "$BUILD_DIR"
    mkdir -p "$OUTPUT_DIR"
}

# Create package structure
create_structure() {
    log_info "Creating package structure..."

    mkdir -p "$BUILD_DIR/package"
    mkdir -p "$BUILD_DIR/package/bin"
    mkdir -p "$BUILD_DIR/package/conf"
    mkdir -p "$BUILD_DIR/package/scripts"
    mkdir -p "$BUILD_DIR/package/lib"
    mkdir -p "$BUILD_DIR/package/share"
}

# Copy package files
copy_files() {
    log_info "Copying package files..."

    # Copy INFO file
    cp "$SPK_DIR/INFO" "$BUILD_DIR/"

    # Copy package icons
    cp "$SPK_DIR/PACKAGE_ICON.PNG" "$BUILD_DIR/" 2>/dev/null || true
    cp "$SPK_DIR/PACKAGE_ICON_256.PNG" "$BUILD_DIR/" 2>/dev/null || true
    cp "$SPK_DIR/PACKAGE_ICON_72.PNG" "$BUILD_DIR/" 2>/dev/null || true

    # Copy configuration files
    cp -r "$SPK_DIR/files/conf/"* "$BUILD_DIR/package/conf/" || true
    cp "$SPK_DIR/conf/pkgctl-php83.sc" "$BUILD_DIR/package/conf/"
    cp "$SPK_DIR/conf/backend.json" "$BUILD_DIR/package/conf/" 2>/dev/null || true
    cp "$SPK_DIR/conf/extensions.json" "$BUILD_DIR/package/conf/" 2>/dev/null || true
    cp "$SPK_DIR/conf/resource.conf" "$BUILD_DIR/package/conf/" 2>/dev/null || true

    # Copy scripts
    cp "$SPK_DIR/src/scripts/"*.sh "$BUILD_DIR/package/scripts/" 2>/dev/null || true
    cp "$SPK_DIR/src/scripts/"*.cgi "$BUILD_DIR/package/scripts/" 2>/dev/null || true

    # Create scripts directory for installation scripts
    mkdir -p "$BUILD_DIR/scripts"

    # Copy installation scripts to root
    for script in preinst postinst preuninst postuninst service-setup start-stop-status; do
        if [ -f "$SPK_DIR/src/scripts/$script" ]; then
            cp "$SPK_DIR/src/scripts/$script" "$BUILD_DIR/scripts/"
            chmod +x "$BUILD_DIR/scripts/$script"
        fi
    done

    # Copy Vue.js wizard files (DSM 7.2.2+)
    if [ -d "$SPK_DIR/src/install-wizard" ]; then
        mkdir -p "$BUILD_DIR/WIZARD_UIFILES"

        # Build the wizard if needed
        if [ -f "$SPK_DIR/src/install-wizard/package.json" ]; then
            log_info "Building Vue.js wizard with webpack..."
            cd "$SPK_DIR/src/install-wizard"
            npm run build > /dev/null 2>&1 || true
            cd "$BUILD_DIR"
        fi

        # Copy main wizard definition file (generated by webpack)
        if [ -f "$SPK_DIR/src/install-wizard/install_uifile" ]; then
            cp "$SPK_DIR/src/install-wizard/install_uifile" "$BUILD_DIR/WIZARD_UIFILES/"
            log_info "Copied install_uifile (Vue.js wizard)"
        fi

        # Copy uninstall wizard if exists
        if [ -f "$SPK_DIR/src/install-wizard/uninstall_uifile" ]; then
            cp "$SPK_DIR/src/install-wizard/uninstall_uifile" "$BUILD_DIR/WIZARD_UIFILES/"
        fi
    fi

    # Copy UI files (DSM configuration panel)
    # dsmuidir="ui" means DSM extracts ui/ FROM package.tgz to /var/packages/php83/ui
    # So UI files must be in BUILD_DIR/package/ui (inside package.tgz)
    if [ -d "$SPK_DIR/src/ui" ]; then
        mkdir -p "$BUILD_DIR/package/ui"
        cp -r "$SPK_DIR/src/ui/"* "$BUILD_DIR/package/ui/" 2>/dev/null || true
        chmod +x "$BUILD_DIR/package/ui/"*.cgi 2>/dev/null || true
        log_info "Copied DSM UI files to package/ui"
    fi

    # Copy utilities
    if [ -d "$SPK_DIR/files/bin" ]; then
        cp "$SPK_DIR/files/bin/"* "$BUILD_DIR/package/bin/" 2>/dev/null || true
    fi

    # Copy icons
    if [ -d "$SPK_DIR/icons" ]; then
        for size in 72 256; do
            if [ -f "$SPK_DIR/icons/php83_${size}.png" ]; then
                cp "$SPK_DIR/icons/php83_${size}.png" "$BUILD_DIR/PACKAGE_ICON_${size}.PNG"
            fi
        done
    fi

    # Copy privilege to conf directory (DSM 7.x requirement)
    mkdir -p "$BUILD_DIR/conf"
    cp "$SPK_DIR/conf/privilege" "$BUILD_DIR/conf/"

    # Copy resource config if exists
    cp "$SPK_DIR/conf/resource.conf" "$BUILD_DIR/conf/" 2>/dev/null || true
}

# Bundle compiled PHP binaries
bundle_php() {
    log_info "Bundling compiled PHP binaries..."

    # Check if PHP binaries exist
    if [ ! -d "$SPK_DIR/files/php" ]; then
        log_error "PHP binaries not found at $SPK_DIR/files/php"
        log_warn "Please run scripts/copy-php-binaries.sh first"
        exit 1
    fi

    # Copy all PHP files (binaries, libraries, extensions)
    log_info "Copying PHP binaries, libraries, and extensions..."
    rsync -av "$SPK_DIR/files/php/" "$BUILD_DIR/package/" | tail -20

    # Verify critical files
    if [ ! -f "$BUILD_DIR/package/bin/php" ]; then
        log_error "PHP binary not found after copy!"
        exit 1
    fi

    if [ ! -f "$BUILD_DIR/package/sbin/php-fpm" ]; then
        log_error "PHP-FPM binary not found after copy!"
        exit 1
    fi

    # Count extensions
    EXT_COUNT=$(ls -1 "$BUILD_DIR/package/lib/php/extensions/no-debug-non-zts-20230831/"*.so 2>/dev/null | wc -l)
    log_info "Bundled $EXT_COUNT PHP extensions"

    # List extensions
    if [ $EXT_COUNT -gt 0 ]; then
        log_info "Available extensions:"
        ls -1 "$BUILD_DIR/package/lib/php/extensions/no-debug-non-zts-20230831/"*.so | \
            sed 's/.*\///' | sed 's/\.so$//' | sort | column -c 100 | sed 's/^/  /'
    fi

    # Create required runtime directories
    mkdir -p "$BUILD_DIR/package/var/sessions"
    mkdir -p "$BUILD_DIR/package/var/tmp"
    mkdir -p "$BUILD_DIR/package/var/log"

    # Fix RPATH for binaries to use relative paths
    log_info "Fixing RPATH for PHP binaries..."
    if [ -f "$SCRIPT_DIR/fix-binaries-rpath.sh" ]; then
        "$SCRIPT_DIR/fix-binaries-rpath.sh" "$BUILD_DIR/package" || log_warn "Failed to fix RPATH, continuing anyway"
    else
        log_warn "fix-binaries-rpath.sh not found, skipping RPATH fix"
    fi

    log_info "PHP binaries bundled successfully"
}

# Fix file and directory permissions
fix_permissions() {
    log_info "Fixing file and directory permissions..."

    cd "$BUILD_DIR"

    # Fix all directories to 755
    log_info "Setting directory permissions to 755..."
    find "$BUILD_DIR/package" -type d -exec chmod 755 {} \;

    # Fix all regular files to 644 (default)
    log_info "Setting file permissions to 644..."
    find "$BUILD_DIR/package" -type f -exec chmod 644 {} \;

    # Fix executable binaries to 755
    log_info "Setting executable permissions..."
    if [ -d "$BUILD_DIR/package/bin" ]; then
        chmod 755 "$BUILD_DIR/package/bin"/*
    fi
    if [ -d "$BUILD_DIR/package/sbin" ]; then
        chmod 755 "$BUILD_DIR/package/sbin"/*
    fi

    # Fix script files to 755
    if [ -d "$BUILD_DIR/package/scripts" ]; then
        find "$BUILD_DIR/package/scripts" -type f \( -name "*.sh" -o -name "*.cgi" \) -exec chmod 755 {} \;
    fi

    # Fix installation scripts to 755
    if [ -d "$BUILD_DIR/scripts" ]; then
        chmod 755 "$BUILD_DIR/scripts"/*
    fi

    # Fix shared libraries permissions (755 for .so files)
    log_info "Setting shared library permissions..."
    find "$BUILD_DIR/package/lib" -type f -name "*.so*" -exec chmod 755 {} \;

    # Fix runtime directory permissions
    # sessions directory needs special permissions (1733 = sticky bit + rwx-wx-wx)
    if [ -d "$BUILD_DIR/package/var/sessions" ]; then
        chmod 1733 "$BUILD_DIR/package/var/sessions"
    fi
    # tmp directory (1777 = sticky bit + rwxrwxrwx)
    if [ -d "$BUILD_DIR/package/var/tmp" ]; then
        chmod 1777 "$BUILD_DIR/package/var/tmp"
    fi
    # log directory (755)
    if [ -d "$BUILD_DIR/package/var/log" ]; then
        chmod 755 "$BUILD_DIR/package/var/log"
    fi

    # Fix configuration files to 644
    if [ -d "$BUILD_DIR/package/etc" ]; then
        find "$BUILD_DIR/package/etc" -type f -exec chmod 644 {} \;
    fi
    if [ -d "$BUILD_DIR/package/conf" ]; then
        find "$BUILD_DIR/package/conf" -type f -exec chmod 644 {} \;
    fi

    # Ensure INFO and other root files have correct permissions
    chmod 644 "$BUILD_DIR/INFO" 2>/dev/null || true
    chmod 644 "$BUILD_DIR"/conf/* 2>/dev/null || true
    chmod 644 "$BUILD_DIR"/PACKAGE_ICON*.PNG 2>/dev/null || true

    log_info "Permission fixing completed"

    # Display permission summary
    log_info "Permission summary:"
    log_info "  Directories: 755 (rwxr-xr-x)"
    log_info "  Regular files: 644 (rw-r--r--)"
    log_info "  Binaries: 755 (rwxr-xr-x)"
    log_info "  Scripts: 755 (rwxr-xr-x)"
    log_info "  Shared libraries: 755 (rwxr-xr-x)"
    log_info "  Sessions dir: 1733 (rwx-wx-wx + sticky)"
    log_info "  Tmp dir: 1777 (rwxrwxrwx + sticky)"
}

# Create package tarball
create_package_tar() {
    log_info "Creating package.tgz..."

    cd "$BUILD_DIR"
    tar czf package.tgz package/

    # Calculate checksum
    PACKAGE_SIZE=$(stat -c%s package.tgz)
    PACKAGE_MD5=$(md5sum package.tgz | cut -d' ' -f1)

    log_info "Package size: $PACKAGE_SIZE bytes"
    log_info "Package MD5: $PACKAGE_MD5"
}

# Prepare scripts (keep as individual files, not tarball)
prepare_scripts() {
    log_info "Preparing scripts directory..."

    cd "$BUILD_DIR"
    # Scripts are already copied to $BUILD_DIR/scripts/
    # Just ensure they have correct permissions
    if [ -d "scripts" ]; then
        chmod 755 "$BUILD_DIR/scripts"
        find "$BUILD_DIR/scripts" -type f -exec chmod 755 {} \;
        log_info "Scripts directory ready with $(ls scripts/ | wc -l) scripts"
    else
        log_warn "No scripts directory found"
    fi
}

# Prepare wizard files (DSM 7.x can use either directory or tarball)
prepare_wizard() {
    log_info "Preparing wizard files..."

    cd "$BUILD_DIR"
    if [ -d "WIZARD_UIFILES" ] && [ "$(ls -A WIZARD_UIFILES)" ]; then
        log_info "Wizard files ready: $(ls WIZARD_UIFILES/ | wc -l) files"
        # Keep WIZARD_UIFILES as directory (DSM 7.x prefers this)
        # No need to create tarball for DSM 7.x
    else
        log_warn "No wizard files found"
    fi
}

# Create final SPK
create_spk() {
    log_info "Creating final SPK package..."

    cd "$BUILD_DIR"

    SPK_NAME="${PKG_NAME}_${PKG_FULL_VERSION}_${PKG_ARCH}.spk"

    # SPK is a tar archive with specific order (DSM 7.x format):
    # 1. INFO (MUST BE FIRST!)
    # 2. PACKAGE_ICON files
    # 3. scripts/ (individual files, not tarball)
    # 4. conf/ (with privilege, resource.conf, etc.)
    # 5. WIZARD_UIFILES/ (directory with install_uifile)
    # 6. package.tgz (MUST BE LAST!)

    # Create tar with POSIX ustar format (not GNU)
    # Note: ui/ is inside package.tgz, not at SPK root level
    tar --format=ustar -cf "$OUTPUT_DIR/$SPK_NAME" \
        INFO \
        $([ -f PACKAGE_ICON.PNG ] && echo "PACKAGE_ICON.PNG") \
        $([ -f PACKAGE_ICON_256.PNG ] && echo "PACKAGE_ICON_256.PNG") \
        $([ -d scripts ] && echo "scripts") \
        $([ -d conf ] && echo "conf") \
        $([ -d WIZARD_UIFILES ] && echo "WIZARD_UIFILES") \
        package.tgz

    SPK_SIZE=$(stat -c%s "$OUTPUT_DIR/$SPK_NAME")
    SPK_MD5=$(md5sum "$OUTPUT_DIR/$SPK_NAME" | cut -d' ' -f1)

    log_info "=================================="
    log_info "SPK created successfully!"
    log_info "Package: $SPK_NAME"
    log_info "Location: $OUTPUT_DIR/$SPK_NAME"
    log_info "Size: $SPK_SIZE bytes ($(numfmt --to=iec-i --suffix=B $SPK_SIZE))"
    log_info "MD5: $SPK_MD5"
    log_info "=================================="
}

# Generate build info
generate_build_info() {
    log_info "Generating build information..."

    cat > "$OUTPUT_DIR/BUILD_INFO.txt" <<EOF
PHP 8.3 Synology Package Build
==============================

Package Name: ${PKG_NAME}
Version: ${PKG_FULL_VERSION}
Architecture: ${PKG_ARCH}
Build Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
Build Host: $(hostname)

Files Generated:
- ${PKG_NAME}_${PKG_FULL_VERSION}_${PKG_ARCH}.spk

Build Notes:
- This is a structure-only build
- PHP binaries need to be compiled separately using spksrc toolchain
- Extensions are managed via the included configuration scripts

Next Steps:
1. Cross-compile PHP 8.3.8 for Geminilake
2. Re-run this script after placing binaries in spk/php83/files/bin/
3. Test installation on DS920+ (or equivalent Geminilake device)

For more information, see specs/001-extension-selection/quickstart.md
EOF

    cat "$OUTPUT_DIR/BUILD_INFO.txt"
}

# Main execution
main() {
    log_info "Starting SPK build for PHP ${PKG_VERSION}"
    log_info "Target architecture: ${PKG_ARCH}"

    clean_build
    create_structure
    copy_files
    bundle_php
    fix_permissions
    create_package_tar
    prepare_scripts
    prepare_wizard
    create_spk
    generate_build_info

    log_info "Build completed successfully!"
}

# Run
main "$@"
